spring:
  application:
    name: todoapp
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/userdb
    username: sa
    password: password
  sql:
    init:
      mode: always
